version: '3.8'

services:
  go-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USER=container-user
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
