apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  # Dummy PostgreSQL connection string (base64 encoded)
  connection-string: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL2RhdGFiYXNlX25hbWU=
