# Minimal values for my-app
# Only sensitive data that needs templating

# Application configuration
app:
  port: "8080"
  user: "Kanav"

# Database connection string (sensitive)
database:
  connectionString: "postgresql://username:password@localhost:5432/database_name"

# Image details (configurable)
image:
  repository: "kanavghai/my-app"
  tag: "latest"
